// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `tools.ozone.verification` namespace.
pub mod defs;
pub mod grant_verifications;
pub mod list_verifications;
pub mod revoke_verifications;
