// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `tools.ozone.verification.defs` namespace.
///Verification data for the associated subject.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct VerificationViewData {
    ///Timestamp when the verification was created.
    pub created_at: crate::types::string::Datetime,
    ///Display name of the subject the verification applies to at the moment of verifying, which might not be the same at the time of viewing. The verification is only valid if the current displayName matches the one at the time of verifying.
    pub display_name: String,
    ///Handle of the subject the verification applies to at the moment of verifying, which might not be the same at the time of viewing. The verification is only valid if the current handle matches the one at the time of verifying.
    pub handle: crate::types::string::Handle,
    ///The user who issued this verification.
    pub issuer: crate::types::string::Did,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub issuer_profile: core::option::Option<
        crate::types::Union<VerificationViewIssuerProfileRefs>,
    >,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub issuer_repo: core::option::Option<
        crate::types::Union<VerificationViewIssuerRepoRefs>,
    >,
    ///Describes the reason for revocation, also indicating that the verification is no longer valid.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub revoke_reason: core::option::Option<String>,
    ///Timestamp when the verification was revoked.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub revoked_at: core::option::Option<crate::types::string::Datetime>,
    ///The user who revoked this verification.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub revoked_by: core::option::Option<crate::types::string::Did>,
    ///The subject of the verification.
    pub subject: crate::types::string::Did,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub subject_profile: core::option::Option<
        crate::types::Union<VerificationViewSubjectProfileRefs>,
    >,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub subject_repo: core::option::Option<
        crate::types::Union<VerificationViewSubjectRepoRefs>,
    >,
    ///The AT-URI of the verification record.
    pub uri: String,
}
pub type VerificationView = crate::types::Object<VerificationViewData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "$type")]
pub enum VerificationViewIssuerProfileRefs {}
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "$type")]
pub enum VerificationViewIssuerRepoRefs {
    #[serde(rename = "tools.ozone.moderation.defs#repoViewDetail")]
    ToolsOzoneModerationDefsRepoViewDetail(
        Box<crate::tools::ozone::moderation::defs::RepoViewDetail>,
    ),
    #[serde(rename = "tools.ozone.moderation.defs#repoViewNotFound")]
    ToolsOzoneModerationDefsRepoViewNotFound(
        Box<crate::tools::ozone::moderation::defs::RepoViewNotFound>,
    ),
}
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "$type")]
pub enum VerificationViewSubjectProfileRefs {}
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "$type")]
pub enum VerificationViewSubjectRepoRefs {
    #[serde(rename = "tools.ozone.moderation.defs#repoViewDetail")]
    ToolsOzoneModerationDefsRepoViewDetail(
        Box<crate::tools::ozone::moderation::defs::RepoViewDetail>,
    ),
    #[serde(rename = "tools.ozone.moderation.defs#repoViewNotFound")]
    ToolsOzoneModerationDefsRepoViewNotFound(
        Box<crate::tools::ozone::moderation::defs::RepoViewNotFound>,
    ),
}
