// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `tools.ozone.verification.revokeVerifications` namespace.
pub const NSID: &str = "tools.ozone.verification.revokeVerifications";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct InputData {
    ///Reason for revoking the verification. This is optional and can be omitted if not needed.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub revoke_reason: core::option::Option<String>,
    ///Array of verification record uris to revoke
    pub uris: Vec<String>,
}
pub type Input = crate::types::Object<InputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    ///List of verification uris that couldn't be revoked, including failure reasons
    pub failed_revocations: Vec<RevokeError>,
    ///List of verification uris successfully revoked
    pub revoked_verifications: Vec<String>,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        Ok(())
    }
}
///Error object for failed revocations
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct RevokeErrorData {
    ///Description of the error that occurred during revocation.
    pub error: String,
    ///The AT-URI of the verification record that failed to revoke.
    pub uri: String,
}
pub type RevokeError = crate::types::Object<RevokeErrorData>;
